spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: kimho
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
jwt-key: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCbG9nIn0.ucIV1H5LjsmblZKyeiz39H1EYsNXZ9tM9PD1qKVMe1lmtpqP0L6eyQhd7I_xsmvB32TcG6h6mg1zwcn6bv3kMg